### ISSUE TITLE
cryptozmas.xyz <> kudos

### ISSUE THREAD

**Issue by Kisgus** [gitcoinco/kudosbadges#125]
# Existing Kudos images we would love to list as "unique" for the Venezuela campaign"

#42 Carlos Matos
#116 Santa's Elf
#118 Merry Kudosmas
#84 Holiday Theme

## Unique versus Rare Christmas Card NFTs

cryptoxmas operate with 2 types of Cards

1. **Unique** customized in collaboration with Dapps,organizations/individuals

1.  **Rare** generated by users either by a) solving small image bounties and receive DAI b) intrinsic motive to support Venezuelans in need

## Meaning of unique NFTs (these images can be Kudos designs or submitted by the dapp themselves)

With unique NFTs, we refer to dapp customized NFTs with the following properties:

- They are minted in collaboration with a partner dapp, organization or individual
- There is only 1 in existence
- They come with "unique" (mainly off-chain) attributes, like the below example:

> "The holder of this Vitalik_Xmas NFT will be entitled to a 1 hour interview with Vitalik Buterin"

## Semi-automized process for creating unique cards via website

**Section on landing page**

![image 2018-12-05 15 05 32](https://user-images.githubusercontent.com/18598519/49518647-7028a300-f89f-11e8-8eeb-cc15e0bbb7a1.jpg)

**Dapp submission form**

(Edit: text/names of buttons changed)

![screen shot 2018-12-05 at 3 08 35 pm](https://user-images.githubusercontent.com/18598519/49518834-e3321980-f89f-11e8-926f-c1d132bcac18.png)

**Manual processing**

We receive image from Dapp, agree on unique attributes and list on webdapp

(Edit: text/names of buttons changed)

**Christmas Cards listings page**

![screen shot 2018-12-05 at 3 11 32 pm](https://user-images.githubusercontent.com/18598519/49518927-183e6c00-f8a0-11e8-8288-324a5fe3f40b.png)

(Edit: text/names of buttons changed)

# Other potential Kudos designs

We have many other ideas for potential Kudos. I am not sure how to proceed, below would be some options, what do you think would be best @ceresstation @owocki ?

a) List ideas in this issue
b) List ideas as individual issues
c) Wait for now, and just start with (forexample) the 4 suggestions above.

**Comment by owocki** [comment]
very excited for this @Kisgus -- what do you need from us to make it happen?  we can prioritize the artwork for the kudos you specified above if you want

**Comment by Kisgus** [comment]
Great to feel your excitement :) I have chatted about the minting process with Scott, and provided him and address you can forward the minted Kudos to. I will also PM it to you. We will then integrate into https://app.cryptoxmas.xyz/

## Kudos

If you have any ideas I would love support in the off-chain world to connect with the coolest dapps/organizations/individuals in the Ethereum space to work with them to generate "unique" kudos based Christmas Cards, that can help incentivize high prices for NFTs.

## Gitcoin

I just had a good experience opening our [first 4 Gitcoin bounties]
(https://github.com/VolcaTech/cryptoxmas.xyz/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)

We also added this extra fundraising addition to the bounties

![screen shot 2018-12-06 at 2 35 33 am](https://user-images.githubusercontent.com/18598519/49555291-ab5abe80-f8ff-11e8-82c0-247e856a4895.png)

Besides opening a few more technical issues, our next step is to open 50+ tiny Gitcoin funded contests for user designed Christmas Cards. We are super open if you have any other ideas?

**Comment by owocki** [comment]
Those all sound great.. Thanks for your comment about Gitcoin bounties :) I hope it goes well, but if you have any Q's scott and I are here to help!

RE: Kudos Christmas Cards, thats actually something that one of the Gitcoin ambassadors has been building too.  https://gitcoinambassadors.github.io/KudoKards/ I can connect you guys if you want.

BTW check the referenced Github issues.  Our designer is starting to submit designs for them!

#42 Carlos Matos
#116 Santa's Elf
#118 Merry Kudosmas
#84 Holiday Theme

**Comment by owocki** [comment]
@Kisgus can you please reach out to me privately so i can send you some of these Kudos to put on the cryptoxmas.xyz site?

cc @ceresstation the kudos are ready
