### ISSUE TITLE
alchemist

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#128]
# Title

alchemist

# Design Inspiration

take the ethos of the mad scientist badge that mladen delivered and make an alchemist one

# Metadata

name: 
description: 
priceFinney: 
numClonesAllowed: 
to_address: 
tags: 
 - tag1
 - tag2

# Down Payment

# Gen0 Owner Address

**Comment by owocki** [comment]
perhaps this could even feature our resident alchemist @austintgriffith on it, if he is so obliged.

**Comment by MladenPetronijevic** [comment]
svg

**Comment by owocki** [comment]
svg http://bits.owocki.com/94de1367e30f/Archive%202019-02-26%20at%201.29.50%20PM.zip

**Comment by owocki** [comment]
https://gitcoin.co/kudos/marketplace/
