### ISSUE TITLE
Nimbus

### ISSUE THREAD

**Issue by Swader** [gitcoinco/kudosbadges#137]
# Title

Nimbus

# Design Inspiration

<img width="1500" alt="header" src="https://user-images.githubusercontent.com/1430603/50952970-44a66300-14b2-11e9-83d4-4cf69d6e34e7.png">

# Metadata

name: Nimbus Contributor
description: You contributed to the next-gen Ethereum 2.0 client: Nimbus.
priceFinney: 50
numClonesAllowed: 50
to_address: 0x04bb33C3A8c2D018836a1f938054Ebb59e0036B2
tags: nimbus, ethereum, sharding, serenity

# Down Payment

https://etherscan.io/tx/0x284f483b7df622254b2b74231e9b4db02ab5fc4305a5730e03296b1f2748b351

# Gen0 Owner Address

0x04bb33C3A8c2D018836a1f938054Ebb59e0036B2

**Comment by Swader** [comment]
I have already designed the assets for this, so not sure if the payment is required? If possible, can I submit another one (into the same issue) for the same deposit? I would like two in total, also asset already designed (just needs to be cropped into the image).

**Comment by owocki** [comment]
cool can you post the asset you designed to this ticket pls?

**Comment by Swader** [comment]
Sweet, thanks!

**Comment by owocki** [comment]
slated for deploy tomorrow; commit 2b2026e53b6cabe0c7962ce551210641041f6dbc

**Comment by Swader** [comment]
Ahh, should it be? If not, I'm good with the way it is.
But I wanted two Kudos - see OP. The Pilot one is the one with wings, and the contributor one is the one you set as pilot. Can we get that fixed and get them both out the door please?

**Comment by owocki** [comment]
oh my bad. yeah we can fix that.

**Comment by owocki** [comment]
https://gitcoin.co/kudos/1107/nimbus_pilot
https://gitcoin.co/kudos/1151/nimbus_contributor

**Comment by Swader** [comment]
Close but no cigar :) The original has different metadata - 50 finney and 50 units max, not 10k. It's supposed to be more prestige given it'll be given to people who helped us kickstart eth2.0 with their contributions. Fixable?

**Comment by Swader** [comment]
@owocki also the images in the marketplace are the same for both (and the rockstar one is failing to load)

![image](https://user-images.githubusercontent.com/1430603/51731641-f087ab00-207b-11e9-96c1-d07b110fd5e9.png)

**Comment by owocki** [comment]
fixing now

**Comment by owocki** [comment]
https://gitcoin.co/kudos/1158/nimbus_contributor
https://gitcoin.co/kudos/1157/nimbus_pilot

3rd time is a charm.. i hope !

**Comment by Swader** [comment]
Going to have to be a fourth time.
Description is wrong on Pilot, and the metadata.

So here goes, both badges, with image and metadata (modified Contributor max count to 500).

## Nimbus Contributor

![](https://user-images.githubusercontent.com/1430603/51039327-5de40800-15b5-11e9-8eaf-c02e2f0d1c12.png)

name: Nimbus Contributor
description: You contributed to the next-gen Ethereum 2.0 client: Nimbus.
priceFinney: 50
numClonesAllowed: 500
to_address: 0x04bb33C3A8c2D018836a1f938054Ebb59e0036B2
tags: nimbus, ethereum, sharding, serenity

## Nimbus Pilot

![](https://user-images.githubusercontent.com/1430603/51039368-72c09b80-15b5-11e9-9d0f-248144de3ed5.png)

name: Nimbus Pilot
description: Awarded for running Nimbus in production
priceFinney: 5
numClonesAllowed: 10000
to_address: 0x04bb33C3A8c2D018836a1f938054Ebb59e0036B2
tags: nimbus, ethereum, sharding, serenity

---

Can I maybe admin those coins if they're attached to my address so I don't bother you any more?

**Comment by owocki** [comment]
> Going to have to be a fourth time. Description is wrong on Pilot, and the metadata.

Ugh, sorry.   Re-minting now

**Comment by owocki** [comment]
https://gitcoin.co/kudos/1161/nimbus_contributor
https://gitcoin.co/kudos/1160/nimbus_pilot

**Comment by Swader** [comment]
Perfect, thank you!

**Comment by Swader** [comment]
@owocki can I get the description in https://gitcoin.co/kudos/1160/nimbus_pilot updated to:

> Awarded for having helped Nimbus mature and go through its growing pains. For testing our documentation, experimental software, and patiently providing us with valuable feedback.

**Comment by owocki** [comment]
@Swader i can update it on gitcoin, but theres no way to do this on IPFS / blockchain (because immutability) without burning the old coin and minting a new one.  that ok?

**Comment by Swader** [comment]
@owocki good enough, thank you, just want to make the info on gitcoin a little clearer, the coin's nature remains the same.

**Comment by owocki** [comment]
updated!

**Comment by Swader** [comment]
Thanks!
