### ISSUE TITLE
Solidity + Vyper

### ISSUE THREAD

**Issue by Swader** [gitcoinco/kudosbadges#138]
Two requests, funding for both sent in one TX.

# Title

Solidity Pro

# Design Inspiration

![](https://solidity.readthedocs.io/en/v0.4.21/_images/logo.svg)

# Metadata

name: Solidity Pro
description: Awarded for a having a notable portfolio of Solidity content, or contributing to the Solidity languge itself.
priceFinney: 200
numClonesAllowed: 100
to_address: 0x4dA2e85D64bEcE663CCaB06E89B970b6b077f22F
tags: solidity, ethereum, serenity, programming

# Down Payment

https://etherscan.io/tx/0xa7b94c24e42ad071d71f428b157fe81b23ca25e6387e79a560ac1d6243fd21e6

# Gen0 Owner Address

0x4dA2e85D64bEcE663CCaB06E89B970b6b077f22F

---

# Title

Vyper Pro

# Design Inspiration

![](https://vyper.readthedocs.io/en/latest/_images/vyper-logo-transparent.svg)

# Metadata

name: Vyper Pro
description: Awarded for a having a notable portfolio of Solidity content, or contributing to the Solidity languge itself.
priceFinney: 200
numClonesAllowed: 100
to_address: 0x4dA2e85D64bEcE663CCaB06E89B970b6b077f22F
tags: solidity, ethereum, serenity, programming

# Down Payment

https://etherscan.io/tx/0xa7b94c24e42ad071d71f428b157fe81b23ca25e6387e79a560ac1d6243fd21e6

# Gen0 Owner Address

0x4dA2e85D64bEcE663CCaB06E89B970b6b077f22F

**Comment by MladenPetronijevic** [comment]
![untitled](https://user-images.githubusercontent.com/41165756/52127253-dc225000-2631-11e9-8285-bf0cf138860b.png)
@Swader could something like this work?

**Comment by Swader** [comment]
Yes, quite, very nice 👍

**Comment by owocki** [comment]
@Swader 
https://gitcoin.co/kudos/1425/vyper_pro
https://gitcoin.co/kudos/1419/solidity_pro

**Comment by Swader** [comment]
Amazing, thanks!
