### ISSUE TITLE
video game themed kudos

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#139]
http://bits.owocki.com/3736a29db14e/Screen%20Shot%202019-01-10%20at%203.12.43%20PM.png

**Comment by Teslow** [comment]
Can this be reopened? 

Edit: I'm a Music Producer & Graphic Designer. I'm interested to see if this Video Game Kudos can still be Greenlit? And if so, flood me with the deets, I gotchu.💯✌

**Comment by FeroxCanis** [comment]
Same here! @Teslow
