### ISSUE TITLE
First grant funded

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#140]
# Title

First grant funded

# Design Inspiration

maybe a gitcoin bot planting a flag with the grants logo on the top of a mountain?

# Metadata

name: 
description: 
priceFinney: 
numClonesAllowed: 
to_address: 
tags: 
 - tag1
 - tag2

# Down Payment

# Gen0 Owner Address

**Comment by MladenPetronijevic** [comment]
![untitled](https://user-images.githubusercontent.com/41165756/53443269-962b9280-3a0b-11e9-8870-2c312503b212.png)

**Comment by owocki** [comment]
looks good to me.  can i have the svg pls @MladenPetronijevic ?

**Comment by owocki** [comment]
http://bits.owocki.com/6d9d35cef68c/first_grant_funded.svg

**Comment by owocki** [comment]
https://gitcoin.co/kudos/marketplace/
