### ISSUE TITLE
Canada Meetup Hacker Badge

### ISSUE THREAD

**Issue by CPSTL** [gitcoinco/kudosbadges#141]
# Title

This badge is for kickoff of the first ever Gitcoin Canada Meetup

# Design Inspiration

Combine a Canadian Maple leaf or a Canadian flag with the Gitcoin logo with a developer on their computer

# Metadata

50 Kudos, 0.02 ETH, and rare/opensource tags

**Comment by MladenPetronijevic** [comment]
@CPSTL 
![untitled](https://user-images.githubusercontent.com/41165756/53246960-5afb2d80-36b2-11e9-86cf-7d3f750fc7f7.png)

**Comment by MladenPetronijevic** [comment]
could something like this work?

**Comment by CPSTL** [comment]
@MladenPetronijevic Yes! It is perfect. Thank you 🥇

**Comment by owocki** [comment]
@MladenPetronijevic CSV pls

**Comment by owocki** [comment]
@CPSTL got any copy we should put in the kudos desc?  is the title the same as the github thread?

**Comment by owocki** [comment]
https://gitcoin.co/kudos/1886/canada_hacker_meetup

**Comment by CPSTL** [comment]
@owocki Amazing. Looking forward to sharing this special kudos to the meetup attendees today 👍

**Comment by owocki** [comment]
cool.  i set it so that only you can send it!
