### ISSUE TITLE
Thapanawat

### ISSUE THREAD

**Issue by Thapanawat003** [gitcoinco/kudosbadges#146]
# Title

# Design Inspiration

<img src='xxxxxxxxxxxxx'>

# Metadata

name: 
description: 
priceFinney: 
numClonesAllowed: 
to_address: 
tags: 
 - tag1
 - tag2

# Down Payment

# Gen0 Owner Address

**Comment by Thapanawat003** [comment]
3683508

**Comment by owocki** [comment]
pls reopen when youve filled out the template

**Comment by Thapanawat003** [comment]
Thx
