### ISSUE TITLE
pokemon-inspired bot kudos

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#212]
https://www.google.com/search?q=top+pokemon&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjSzY_A9J3hAhUDNd8KHY15DjcQ_AUIDigB&biw=1280&bih=1306#imgrc=PCBcBE9hrzyBeM:

**Comment by yash412** [comment]
Made the PR with these 8 Kudos, let me know of any changes. 

![bullbasaur](https://user-images.githubusercontent.com/21294773/55006775-59918d80-4fef-11e9-9aa6-c8f85d8d37c3.png)
![charmander](https://user-images.githubusercontent.com/21294773/55006776-59918d80-4fef-11e9-9b1a-f3d6bb435099.png)
![eevee](https://user-images.githubusercontent.com/21294773/55006778-5a2a2400-4fef-11e9-93d7-c80c25923bd3.png)
![jigglypuff](https://user-images.githubusercontent.com/21294773/55006780-5a2a2400-4fef-11e9-90d0-b2fe1195d440.png)
![meowth](https://user-images.githubusercontent.com/21294773/55006782-5ac2ba80-4fef-11e9-86fd-48037fdfae86.png)
![pidgey](https://user-images.githubusercontent.com/21294773/55006784-5ac2ba80-4fef-11e9-8383-8e597993d807.png)
![pikachu](https://user-images.githubusercontent.com/21294773/55006786-5ac2ba80-4fef-11e9-9a9a-11cab0a24d87.png)
![snorlax](https://user-images.githubusercontent.com/21294773/55006787-5b5b5100-4fef-11e9-9fb2-0f65740e4b84.png)

**Comment by owocki** [comment]
these are really cool :)

want me to hold off on merging them in until we open up another bounty for kudos designs?

**Comment by yash412** [comment]
@owocki oh that's closed? Nah, go ahead it's alright. 👍

**Comment by owocki** [comment]
@yash412 want to PR a change to kudos.yaml that means that you own the kudos and get the rewards when ppl purchase them?

**Comment by yash412** [comment]
@owocki nah it's alright as long as I get credits for making the kudos on the purchase end I'm good. I'm a little confused as to whether or not you're processing a payout for this though?

**Comment by owocki** [comment]
not planning on it no.. ill update the YAML file so that you get credit for purchases.

**Comment by yash412** [comment]
@owocki only asked cause you mentioned it yourself I had agreed to not getting paid for this 💸 
Nonetheless, I'll edit the YAML file don't worry.

**Comment by owocki** [comment]
cool minting now

**Comment by owocki** [comment]
live on https://gitcoin.co/kudos/marketplace/

**Comment by owocki** [comment]
@yash412 fwiw it looks like hte left side is cut off on these http://bits.owocki.com/56e1782b2922/Image%202019-04-12%20at%2011.12.47%20AM.png

**Comment by yash412** [comment]
@owocki oh darn, I currently don't have access to my laptop with all the files, will submit a PR with the changes in 2-3 days. :')
