### ISSUE TITLE
MESH Token - Initial Kudos

### ISSUE THREAD

**Issue by orbro** [gitcoinco/kudosbadges#217]
# Timeline
No rush

# Title
* MESH Token Closed Beta Participant
* MESH Token Season 0 Participant
* MESH Token Season 0 Top Performer
* MESH Token Season 0 All-Star

# Design Inspiration
* [Closed Beta](https://thenounproject.com/search/?q=beta&i=1955900)
* [Participant](https://thenounproject.com/search/?q=participation&i=1686762)
* [Top Performer](https://thenounproject.com/search/?q=participation&i=1187499)
* [All-star](https://thenounproject.com/search/?q=participation&i=1188860)

(open to other suggestions)

# Metadata

```
- name: [MESH Token Closed Beta Participant, MESH Token Season 0 Participant, MESH Token Season 0 Top Performer, MESH Token Season 0 All-Star]
- description: [Participated in the MESH Token Closed Beta, Participated in MESH Token Season 0, Achieved a top 10 ranking in the MESH Token leaderboards for Season 0, Achieved the highest possible ranking in the MESH Token leaderboards for Season 0]
- numClonesAllowed (positive integer): [100, 1000, 100, 10]
```

# Gen0 Owner Address

0xF9963dbe9438A5ECb62e5e7c2C081C3d12D48dd5

**Comment by owocki** [comment]
hey @orbro whats your budget look like?  usually we charge 0.5 ETH per design we do; happy to give a break on pricing since it's internal, but it's also nice to show demand / revenue to finance!

**Comment by orbro** [comment]
@owocki we don't have a budget, unfortunately :( any chance we could just make the artwork suuuuper simple so there's little to no lift on your end?

**Comment by owocki** [comment]
can we put those assets into svg template and PR them back to this repo?

http://bits.owocki.com/e0d4f26f5a76/kudos_template.svg

**Comment by owocki** [comment]
lmk
