### ISSUE TITLE
Dai Kudos Friday! :)

### ISSUE THREAD

**Issue by Lenkla** [gitcoinco/kudosbadges#261]
# Timeline
@owocki it is short notice but if this week you could put a simple Dai Kudo out that would be amazing!

# Title
Dai Kudos

# Design Inspiration
https://github.com/makerdao/Overview-of-MakerDAO-design/tree/master/DAI

# Metadata
https://makerdao.com
https://alpha.kickback.events/event/0x0fdcc441854738e8579a479ca5dca86e147165f4

**Comment by owocki** [comment]
https://gitcoin.co/kudos/4536/dai

image will show up in a sec once this deploy goes out
