### ISSUE TITLE
Dapp Univeristy: "Blockchain Mastery University" NFT Badge

### ISSUE THREAD

**Issue by gwmccubbin** [gitcoinco/kudosbadges#276]
@owocki Just following up re our conversation. I'm trying to create an NFT badge for "Blockchain Mastery University" a la Gitcoin kudos. 🙏Thanks!!

# Timeline
January 20, 2019

# Title
Blockchain Mastery University

# Design Inspiration
This NFT badge is for members of my new program "Blockchain Mastery University". I would like to include my logo on this badge:

https://www.dropbox.com/s/yymrizbfsadwv9b/logo_transparent.png?dl=0

Bonus points If it's possible to also convey "mastery" with the badge artwork.

Here are a few kudos badges that I like:
https://gitcoin.co/kudos/1903/blockchain_pro
https://gitcoin.co/kudos/66/ruby_on_rails_master
https://gitcoin.co/kudos/54/javascript_master_scriber

# Metadata
```
- name: Blockchain Mastery University
  description: You're on your way to becoming an in-demand blockchain master!
```

# Down Payment
https://etherscan.io/tx/0x70211ae2d0ec4d8bbf430beb2bf0c81f23c3fc856b29a6022104d847e0aa9a66

# Gen0 Owner Address
0xbFCada1753097b8370D947d30154FdDCC281cEba

**Comment by owocki** [comment]
well get right on these!

**Comment by owocki** [comment]
@MladenPetronijevic hows this going?

**Comment by MladenPetronijevic** [comment]
[blockchain_mastery_university.zip](https://github.com/gitcoinco/kudosbadges/files/4082637/blockchain_mastery_university.zip)

**Comment by MladenPetronijevic** [comment]
@owocki is it this one?

**Comment by gwmccubbin** [comment]
Looks good to me. Thanks guys!

**Comment by owocki** [comment]
here ya go @gwmccubbin https://gitcoin.co/kudos/10796/blockchain_mastery_university

this is owned by you at 0x6239FF1040E412491557a7a02b2CBcC5aE85dc8F
