### ISSUE TITLE
MythXperts - Apprentice badge

### ISSUE THREAD

**Issue by EtherDotBlue** [gitcoinco/kudosbadges#284]
# Timeline
Feb 10th in time for ETH Denver

# Title
MythXperts - Apprentice badge

# Design Inspiration
MythXperts - Apprentice badge is the first of a series of three badges for devs who have shown expertise in MythX.  Apprentice, Maven and Master.  We want the blue MythX logo in there in  some way.  We also want them to all be part of a family with similar design.  It can be Japanese, space related, jedi, etc - we love your designs!

If you can make all three at the same time it would be awesome, and I can send more ETH, but the Apprentice level is the first we will give out ASAP.  We are also going to make stickers and need the master file for that.

# Down Payment
https://etherscan.io/tx/0x6433769d53c9740e4e74330c559e7d0dcbeb78fa72c416909007ab1f42349271

# Gen0 Owner Address
0xEd40A5d69E4754c111867A9D15475A5388fFd6F1

**Comment by owocki** [comment]
@MladenPetronijevic can u hook it up

**Comment by EtherDotBlue** [comment]
@MladenPetronijevic and @owocki getting close now - any news on this one?  I want to make some stickers too if possible.

**Comment by owocki** [comment]
@MladenPetronijevic bump

**Comment by MladenPetronijevic** [comment]
![Untitled](https://user-images.githubusercontent.com/41165756/73946638-880e1380-48f6-11ea-8469-35679a1a4a21.png)
could something like this work?

**Comment by EtherDotBlue** [comment]
@MladenPetronijevic Thanks.  This could work.  It needs to say MythXpert instead of MythX though. 
  Since there are three levels total and they are named after personas (Apprentice, Maven and Master), I was hoping there could be a cool human (or robot) element in there.  Like these for example.  Possible? 
https://gitcoin.co/dynamic/kudos/4282/oracle
https://s.gitcoin.co/static/v2/images/kudos/kendo-bot.42e053af5dfe.svg
https://gitcoin.co/dynamic/kudos/4179/fourth_of_july_bot

**Comment by MladenPetronijevic** [comment]
@EtherDotBlue sure thing, i'll give it a try

**Comment by MladenPetronijevic** [comment]
![Untitled](https://user-images.githubusercontent.com/41165756/73999240-65b2df00-4964-11ea-8378-5bcc16af5629.png)
@EtherDotBlue something like this?

**Comment by EtherDotBlue** [comment]
@MladenPetronijevic @owocki Yes, that will do the trick - thank you so much!  OK, let's get this locked and loaded so we can send these out at ETHDenver when people pass the challenge.  @owocki can you pint me to the latest guide for the distribution options of kudos?

**Comment by owocki** [comment]
@EtherDotBlue  i will mint it for you this weekend.  do you want us to be able to airdrop it?  or do you want to send it manually through Gitcoin's web interface?

**Comment by EtherDotBlue** [comment]
Thanks @owocki I need to be able to send them out once someone passes the challenge and becomes a MythXpert.  So manual.  Thanks.

**Comment by owocki** [comment]
@MladenPetronijevic can i have the svg for said kudos?

**Comment by MladenPetronijevic** [comment]
[mythxpert.zip](https://github.com/gitcoinco/kudosbadges/files/4181416/mythxpert.zip)
@owocki

**Comment by owocki** [comment]
@MladenPetronijevic looks great but tom wanted 3 badges.. Apprentice, Maven and Master

can u create the maven and master badges?

@EtherDotBlue since the apprentice level is done (see above comment) can u upload it to https://gitcoin.co/kudos/new with the right title/copy/ num clones? (note this is a new tool we created to make kudos minting easier - id submit it for you but i dont know the title/desc/clone count for the badges)

**Comment by MladenPetronijevic** [comment]
@owocki sure thing

**Comment by EtherDotBlue** [comment]
@owocki Done - see below.  @MladenPetronijevic I don't think anyone will make it past apprentice at ETHDenver, so no need to rush the other two level.  Thanks again.

Here is the meta data:
name: MythXperts Apprentice 
description: MythXperts have shown exceptional skill in using MythX tools to detects vulnerabilities in smart contracts and are on their way to becoming Masters.  
artist: Ether Blue  
priceFinney: 100  
numClonesAllowed: 1000  
to_address: 0xEd40A5d69E4754c111867A9D15475A5388fFd6F1
can_be_sent_by: 0xEd40A5d69E4754c111867A9D15475A5388fFd6F1
marketplace_listed: False  
tags:
   • MythXperts
   • Smart contracts
   • Security

**Comment by MladenPetronijevic** [comment]
![Untitled](https://user-images.githubusercontent.com/41165756/74207754-21d01a80-4c81-11ea-9133-6335e4c09a33.png)

**Comment by MladenPetronijevic** [comment]
@EtherDotBlue i've just finished these two, let me know if there are any changes needed

**Comment by owocki** [comment]
@EtherDotBlue https://gitcoin.co/kudos/10852/mythxperts_apprentice

let us know what u think of the ones above too!

**Comment by EtherDotBlue** [comment]
@owocki Done - see below. @MladenPetronijevic  Oh my - very sexy.  Those will work just fine - thanks!

All the metadata is the same except for:
name: MythXperts Maven
description: MythXperts who have surpassed the Apprentice Level and are wise indeed in the way of automated smart contract security analysis, answering questions and issues in the MythX Forum.  

name: MythXperts Masters
description:  The highest level of MythXpert mastery rivaling that of our own engineering team.  The most active in the community and able to join certain paid challenges and quests

**Comment by owocki** [comment]
@MladenPetronijevic can i has svgs

**Comment by MladenPetronijevic** [comment]
@owocki 
[mythxpert_kudos.zip](https://github.com/gitcoinco/kudosbadges/files/4187719/mythxpert_kudos.zip)

**Comment by owocki** [comment]
https://gitcoin.co/kudos/10871/mythxperts_masters
https://gitcoin.co/kudos/10875/mythxperts_maven
