### ISSUE TITLE
empathetic

### ISSUE THREAD

**Issue by owocki** [gitcoinco/kudosbadges#68]
# Title

# Design Inspiration

http://bits.owocki.com/a97ba0b11869/Screen%20Shot%202018-11-03%20at%206.27.48%20PM.png

# Metadata

description: 
rarity: 
priceFinney: 
numClonesAllowed: 
tags: 

# Down Payment

# Gen0 Owner Address

**Comment by agnelvishal** [comment]
The design inspiration link seems to be broken for me

**Comment by owocki** [comment]
yes; closing it now
